config/routes.rb
Restaurente::Application.routes.draw do
  resources :tables

  resources :rols
  resources :receta

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  post '/user/save' => 'rols#save'
  get '/users/create_user' => 'rols#create_user'
  get '/users/remove/:id' => 'rols#remove'
  post '/user' => 'users#create'

  get '/users/edit_user/:id' => 'rols#edit_user'

 get '/admi' => 'rols#admi'
 get '/cuentas' => 'rols#cuentas'
 
 get '/asistente' => 'rols#asistente'
 get '/chef' => 'rols#chef'
 get '/mesero' => 'rols#mesero'
 get '/barman' => 'rols#barman'
 

  get '/admi/user/role_admi/:id' => 'rols#role_admi', :as => 'role_admi'
  get '/admi/user/role_asistente/:id' => 'rols#role_asistente', :as => 'role_asistente'
  get '/admi/user/role_barman/:id' => 'rols#role_barman', :as => 'role_barman'
  get '/admi/user/role_mesero/:id' => 'rols#role_mesero', :as => 'role_mesero'
  get '/admi/user/role_chef/:id' => 'rols#role_chef', :as => 'role_chef'

  root 'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/contact', to: 'static_pages#contact',  via: 'get'

 

end

app/models/rol.rb
class Rol < ActiveRecord::Base
belongs_to :User
end

app/controllers/rols_controller.rb
class RolsController < ApplicationController
  before_action :set_rol, only: [:show, :edit, :update, :destroy]
   skip_before_filter :verify_authenticity_token

  # GET /rols
  # GET /rols.json
  def index
    @rols = Rol.all

    if user_signed_in? && current_user.rol_id == 1
      redirect_to '/admi'
       @users = User.all
    else
      if  user_signed_in? &&  current_user.rol_id == 2
         redirect_to '/asistente'
      end  
      if  user_signed_in? &&  current_user.rol_id == 3
         redirect_to '/barman'
      end
      if  user_signed_in? &&  current_user.rol_id == 4
         redirect_to '/mesero'
      end    
      if  user_signed_in? &&  current_user.rol_id == 5
         redirect_to '/chef'
      end 
    end
  end

def home
    if current_user.rol_id != 1
      @users = User.all
    else
      redirect_to '/'
    end
  end


  # GET /rols/1
  # GET /rols/1.json
  def show
  end

  # GET /rols/new
  def new
    @rol = Rol.new
  end

  # GET /rols/1/edit
  def edit
  end







def role_admi
    @user=User.find(params[:id])
    @user.rol_id = 1
    @user.save
    redirect_to :back
  end

  def role_asistente
    @user=User.find(params[:id])
    @user.rol_id = 2
    @user.save
    redirect_to :back
  end

  def role_barman
    @user=User.find(params[:id])
    @user.rol_id = 3
    @user.save
    redirect_to :back
  end

  def role_mesero
    @user=User.find(params[:id])
    @user.rol_id = 4
    @user.save
    redirect_to :back
  end

def role_chef
    @user=User.find(params[:id])
    @user.rol_id = 5
    @user.save
    redirect_to :back
  end


 
  def admi
    if current_user.rol_id == 1
     
     if params[:search]
      @users = User.search(params[:search])
    else
      @users = User.all  
    end
   else
    redirect_to '/'
   end
  end




  def remove
    @user=User.find(params[:id])
    @user.destroy
    redirect_to :back
  end

  def save
      @users=User.all
      @user=User.new
      @user.email=params[:email]
      @user.password=params[:password]
      @user.name = params[:name]
      @user.lastname = params[:lastname]
      @user.telf = params[:telf]
      @user.rol_id = 4 #por defecto creamos meseros
      @users.each do |user|
       if @user.email == user.email
        create_user
       end
      end
      @user.save
      redirect_to '/'
  end

  def edit_user
    @user=User.find(params[:id])
  end

  def create_user
    @user=User.new
  end

  def cuentas
    @users = User.all
  end




  # POST /rols
  # POST /rols.json
  def create
    @rol = Rol.new(rol_params)

    respond_to do |format|
      if @rol.save
        format.html { redirect_to @rol, notice: 'Rol was successfully created.' }
        format.json { render action: 'show', status: :created, location: @rol }
      else
        format.html { render action: 'new' }
        format.json { render json: @rol.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rols/1
  # PATCH/PUT /rols/1.json
  def update
    respond_to do |format|
      if @rol.update(rol_params)
        format.html { redirect_to @rol, notice: 'Rol was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @rol.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rols/1
  # DELETE /rols/1.json
  def destroy
    @rol.destroy
    respond_to do |format|
      format.html { redirect_to rols_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rol
      @rol = Rol.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rol_params
      params.require(:rol).permit(:name)
    end
end

app/helpers/rols_helper.rb
module RolsHelper
end

app/views/rols/_form.html.erb
<%= form_for(@rol) do |f| %>
  <% if @rol.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rol.errors.count, "error") %> prohibited this rol from being saved:</h2>

      <ul>
      <% @rol.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, 'Nombre' %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit 'Crear Rol' %>
  </div>
<% end %>

app/views/rols/_form2.html.erb
<% if @user.errors.any? %>
<%= @user.errors.full_messanges.each do |msg| %>
   <li><%= msg %></li>
   <% end %>
<% end %>
<div class="panel panel-success">
  <div class="panel-heading">
    <h3 class="panel-title"></h3>
  </div>
  <div class="panel-body">
    <div class="container">

      	<form action="/user/save" method="post" class="form-horizontal" role="form">
         <div class="form-group">
          <label for="inputName3" class="col-sm-2 control-label">Nombre(s)</label>
          <div class="col-sm-7">
            <input type="text" class="textboxgrade" id="inputEmail3" placeholder="Nombre(s)" required="required" name="name" value="<%= @user.name %>">
          </div>
        </div>
        <div class="form-group">
          <label for="inputLastname3" class="col-sm-2 control-label">Apellidos</label>
          <div class="col-sm-7">
            <input type="text" class="textboxgrade" id="inputEmail3" placeholder="Apellidos" required="required" name="lastname" value="<%= @user.lastname %>">
          </div>
        </div>

        <div class="form-group">
          <label for="inputLastname3" class="col-sm-2 control-label">Telefono</label>
          <div class="col-sm-7">
            <input type="number" class="textboxgrade" id="inputEmail3" placeholder="Telefono" required="required" name="telf" value="<%= @user.telf %>">
          </div>
        </div>


        <div class="form-group">
          <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
          <div class="col-sm-7">
            <input type="email" class="textboxgrade" id="inputEmail3" placeholder="Email" required="required" name="email" value="<%= @user.email %>">
          </div>
        </div>
        <div class="form-group">
          <label for="inputPassword3" class="col-sm-2 control-label">Password</label>
          <div class="col-sm-7">
            <input type="password" class="textboxgrade" id="inputPassword3" placeholder="Password" name="password" value ="<%= @user.password %>" required="required">
          </div>
        </div>

        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-7">
        </div>
        </div>
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-7">
             <input type="submit" name="commit" value="Save" class="btn btn-success">
          </div>
        </div>
      </form>
    </div>
  </div>
</div>

app/views/rols/admi.html.erb
 <center><h1><b> Administrador </b></h1></center> 
 <a href= "/cuentas" class="btn btn-success active"><h5><b> -Gestionar Cuenta-</b></h5></a>
 <br>
 <br>
 <a href= "/" class="btn btn-success active"><h5><b> -Gestionar Receta-</b></h5></a>

app/views/rols/asistente.html.erb
 <center><h1><b> Asistente </b></h1></center> 

app/views/rols/barman.html.erb
 <center><h1><b> Barman </b></h1></center> 
 <a href= "/" class="btn btn-success active"><h5><b> -Gestionar Receta-</b></h5></a>

app/views/rols/chef.html.erb
 <center><h1><b> Chef </b></h1></center> 
<%= link_to '-Gestionar Receta-', receta_path, :class => "btn btn-default"  %> 

app/views/rols/create_user.html.erb
<h2>Crear Usuario</h2>
<br> 
<%= render 'form2' %>

app/views/rols/cuentas.html.erb
  <center><h1><b> Administracion de Cuentas </b></h1></center> 
  <br>
<a href= "/users/create_user" class="btn btn-success active"><h5><b> -Crear Usuario-</b></h5></a>

<DIV ALIGN=right><p id="notice"><%= notice%></p>
    <%= form_tag '/admi', :method => 'get' do %>
      <h2><b><%= label_tag "Buscar Usuario   " %></b></h2>
      <h5><%= text_field_tag :search %>
      <%= submit_tag "Buscar", :name => nil, :class => 'btn' %></h5> 
<% end %>

</DIV>


<h1><b>Cuentas</b></h1>

<div class="panel panel-success">

      <table class="table table-striped"><thead>
          <tr class="info">
       
          <td><b>Email</b></td>
          <th></th>
          <td><b>Rol</b></td>
          <td><b>Creado</b></td>
          <td></td>
          <td><b>Asignar Rol</b></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td><b align ="center">Opciones</b></td>

            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <tr>
          <% @users.each do |user| %>
          <tr>
            <% if user.rol_id != 1 %>
            <%@a = Rol.find(user.rol_id)%>
              <td><%= user.email %></td> 
              <td></td>
              <td><%= @a.name%></td> 
              <td><%= user.created_at %></td>

              
              <td><h5><a href= "<%=role_asistente_path(user.id) %>"class="btn btn-info"><b>Asistente</b></h5></a></td>  
              <td><h5><a href= "<%=role_barman_path(user.id) %>"class="btn btn-success"><b>Barman</b></h5></a></td>  
              <td><h5><a href= "<%=role_mesero_path(user.id) %>"class="btn btn-default"><b>Mesero</b></h5></a></td> 
              <td><h5><a href= "<%=role_chef_path(user.id) %>"class="btn btn-primary"><b>Chef</b></h5></a></td>  
            

              <td></td> 
              <td><h5><a href= "/users/edit_user/<%=user.id%>" class="btn btn-info"><b>Ver Usuario</b></h5></a></td>
              <td><h5><a href= "/users/remove/<%=user.id%>" class="btn btn-danger"><b>Eliminar</b></h5></a></td>
              <td><h5><a href= "/users/edit_user/<%=user.id%>" class="btn btn-warning"><b>Editar</b></h5></a></td>  
            <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>

</div>

app/views/rols/edit.html.erb
<h1>Editar Rol</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @rol %> |
<%= link_to 'Atras', rols_path %>

app/views/rols/edit_user.html.erb
<h2>Editar Usuario</h2>
<br> 
<%= render 'form2' %>

app/views/rols/index.html.erb
<!-- <center><h1><i>Bienvenidos a Innova!!!</i></h1></center>
  <center><iframe width="560" height="315" src="//www.youtube.com/embed/9BzINf6RQtY" frameborder="0" allowfullscreen></iframe></center>

app/views/rols/mesero.html.erb
 <center><h1><b> Mesero </b></h1></center> 

app/views/rols/new.html.erb
<h1>Nuevo Rol</h1>

<%= render 'form' %>

<%= link_to 'Atras', rols_path %>

app/views/rols/show.html.erb
<h1>Ver Rol</h1>

<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @rol.name %>
</p>

<%= link_to 'Editar', edit_rol_path(@rol) %> |
<%= link_to 'Atras', rols_path %>