config/routes.rb
Restaurente::Application.routes.draw do
  resources :tables

  resources :rols
  resources :receta

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  post '/user/save' => 'rols#save'
  get '/users/create_user' => 'rols#create_user'
  get '/users/remove/:id' => 'rols#remove'
  post '/user' => 'users#create'

  get '/users/edit_user/:id' => 'rols#edit_user'

 get '/admi' => 'rols#admi'
 get '/cuentas' => 'rols#cuentas'
 
 get '/asistente' => 'rols#asistente'
 get '/chef' => 'rols#chef'
 get '/mesero' => 'rols#mesero'
 get '/barman' => 'rols#barman'
 

  get '/admi/user/role_admi/:id' => 'rols#role_admi', :as => 'role_admi'
  get '/admi/user/role_asistente/:id' => 'rols#role_asistente', :as => 'role_asistente'
  get '/admi/user/role_barman/:id' => 'rols#role_barman', :as => 'role_barman'
  get '/admi/user/role_mesero/:id' => 'rols#role_mesero', :as => 'role_mesero'
  get '/admi/user/role_chef/:id' => 'rols#role_chef', :as => 'role_chef'

  root 'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/contact', to: 'static_pages#contact',  via: 'get'

 

end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  before_action :set_table, only: [:show, :edit, :update, :destroy]

  # GET /tables
  # GET /tables.json
  def index
    @tables = Table.all
  end

  # GET /tables/1
  # GET /tables/1.json
  def show
  end

  # GET /tables/new
  def new
    @table = Table.new
  end

  # GET /tables/1/edit
  def edit
  end

  # POST /tables
  # POST /tables.json
  def create
    @table = Table.new(table_params)

    respond_to do |format|
      if @table.save
        format.html { redirect_to @table, notice: 'Table was successfully created.' }
        format.json { render action: 'show', status: :created, location: @table }
      else
        format.html { render action: 'new' }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tables/1
  # PATCH/PUT /tables/1.json
  def update
    respond_to do |format|
      if @table.update(table_params)
        format.html { redirect_to @table, notice: 'Table was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tables/1
  # DELETE /tables/1.json
  def destroy
    @table.destroy
    respond_to do |format|
      format.html { redirect_to tables_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_table
      @table = Table.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def table_params
      params.require(:table).permit(:state)
    end
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/tables/_form.html.erb
<%= form_for(@table) do |f| %>
  <% if @table.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@table.errors.count, "error") %> prohibited this table from being saved:</h2>

      <ul>
      <% @table.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :state, 'Estado' %><br>
    <%= f.text_field :state %>
  </div>
  <div class="actions">
    <%= f.submit 'Crear Mesa' %>
  </div>
<% end %>

app/views/tables/edit.html.erb
<h1>Editar Mesa</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @table %> |
<%= link_to 'Atras', tables_path %>

app/views/tables/index.html.erb
<h1>Ver Lista de Mesas</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Estado</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tables.each do |table| %>
      <tr>
        <td><%= table.state %></td>
        <td><%= link_to 'Mostrar', table %></td>
        <td><%= link_to 'Editar', edit_table_path(table) %></td>
        <td><%= link_to 'Eliminar', table, method: :delete, data: { confirm: 'Esta seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Mesa', new_table_path %>

app/views/tables/new.html.erb
<h1>Crear Mesa</h1>

<%= render 'form' %>

<%= link_to 'Atras', tables_path %>

app/views/tables/show.html.erb
<h1>Ver Mesa</h1>
<p id="notice"><%= notice %></p>

<p>
  <strong>Estado:</strong>
  <%= @table.state %>
</p>

<%= link_to 'Editar', edit_table_path(@table) %> |
<%= link_to 'Atras', tables_path %>