config/routes.rb
Restaurente::Application.routes.draw do
  resources :tables

  resources :rols
  resources :receta

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  post '/user/save' => 'rols#save'
  get '/users/create_user' => 'rols#create_user'
  get '/users/remove/:id' => 'rols#remove'
  post '/user' => 'users#create'

  get '/users/edit_user/:id' => 'rols#edit_user'

 get '/admi' => 'rols#admi'
 get '/cuentas' => 'rols#cuentas'
 
 get '/asistente' => 'rols#asistente'
 get '/chef' => 'rols#chef'
 get '/mesero' => 'rols#mesero'
 get '/barman' => 'rols#barman'
 

  get '/admi/user/role_admi/:id' => 'rols#role_admi', :as => 'role_admi'
  get '/admi/user/role_asistente/:id' => 'rols#role_asistente', :as => 'role_asistente'
  get '/admi/user/role_barman/:id' => 'rols#role_barman', :as => 'role_barman'
  get '/admi/user/role_mesero/:id' => 'rols#role_mesero', :as => 'role_mesero'
  get '/admi/user/role_chef/:id' => 'rols#role_chef', :as => 'role_chef'

  root 'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/contact', to: 'static_pages#contact',  via: 'get'

 

end

app/views/layouts/_footer.html.erb
<footer class="panel-footer navbar-default navbar-fixed-bottom">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <font color="black"> <h4>Siguenos:</h4> </font>
        <a href="https://www.facebook.com/elfogondemaria?fref=ts"><img src="/images/facebook.png" width="20" /></a>
      </div>    
      <div class="col-xs-6">
        <div align="right">
          <%= link_to " Contactenos ", 'contact' %> </li>
        </div>
      </div>  
    </div>

    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <font color="black"> <center>Taller de Sistemas de Informacion - © 2014 </center> </font>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse navbar-static-top" role="navigation">
	<div class="navbar-inner">
		<div class="container">
			<div class="navbar-header">
				<a href=" <%= root_path %> "> <img src="/images/logo_fogon.png" width="90"/> </a>
			</div>

			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<% if current_user %>
						<li> <%= link_to 'Mesa', '/tables' %> </li>
						<li> <%= link_to 'Receta', '/receta' %> </li>
						<li> <%= link_to 'Pedido', '#' %> </li>
					<% end %>
				</ul>

				<ul class="nav navbar-nav navbar-right">
					<%if current_user %>
            			<li><%= link_to current_user.name.capitalize, edit_registration_path(current_user) %></li>
            			<li><%= link_to "Salir", destroy_user_session_path %></li>
          			<%else%>
            			<li> <%= link_to "Registrarse", new_user_registration_path %> </li>
            			<li> <%= link_to "Iniciar sesión", new_user_session_path %> </li>
          			<%end%>
				</ul>
			</div>
		</div>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!--meta charset="utf-8"-->
  <title>Restaurante</title>
  <!--link rel="stylesheet" href="/app/assets/stylesheets/bootstrap.min.css"-->
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <br>
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
  
  <!--script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="/app/assets/javascripts/bootstrap.min.js"></script-->
</body>
</html>